CREATE TABLE ticket (
   ticket_id INTEGER,
   ticket_price NUMERIC(15,2)  ,
   ticket_name VARCHAR(50) , 
   ticket_value VARCHAR(50) ,
   PRIMARY KEY(ticket_id)
);


CREATE TABLE Dinosaur(
   dinosaur_ID INTEGER,
   dinosaur_name VARCHAR(50) ,
   dinosaur_diet  VARCHAR(50) ,
   dinosaur_species VARCHAR(50) ,
   dinosaur_description VARCHAR(1500) ,
   dinosaur_resume VARCHAR(50) ,
   dinosaur_available BOOLEAN,
   PRIMARY KEY(dinosaur_ID)
);

CREATE TABLE Utilisateur(
   user_id INTEGER,
   user_admin BOOLEAN,
   user_first_name VARCHAR(50) ,
   user_surname VARCHAR(50) ,
   user_birthdate DATE,
   user_adress VARCHAR(50) ,
   user_mail VARCHAR(50) ,
   user_password VARCHAR(100) ,
   PRIMARY KEY(user_id)
);

CREATE TABLE Réservation(
   reservation_id INTEGER,
   reservation_date DATE,
   user_id INTEGER NOT NULL,
   PRIMARY KEY(reservation_id),
   FOREIGN KEY(user_id) REFERENCES Utilisateur(user_id)
);

CREATE TABLE ticket_dinosaur(
   ticket_id INTEGER,
   dinosaur_ID INTEGER,
   PRIMARY KEY(ticket_id, dinosaur_ID),
   FOREIGN KEY(ticket_id) REFERENCES ticket (ticket_id),
   FOREIGN KEY(dinosaur_ID) REFERENCES dinosaur(dinosaur_ID)
);

CREATE TABLE reservation_ticket(
   reservation_id INTEGER,
   ticket_id INTEGER,
   PRIMARY KEY(reservation_id, ticket_id),
   FOREIGN KEY(reservation_id) REFERENCES Réservation(reservation_id),
   FOREIGN KEY(ticket_id) REFERENCES ticket (ticket_id)
);


-- dinosaurS -- 

-- Jeu de données pour la table "dinosaur"
-- Il est courant d'utiliser une seule instruction INSERT INTO avec plusieurs tuples de valeurs
-- pour des raisons de performance et de lisibilité.

INSERT INTO dinosaur (dinosaur_ID, dinosaur_name, dinosaur_diet, dinosaur_species, dinosaur_description, dinosaur_resume, dinosaur_available) VALUES
(1, 'Goliath', 'Carnivore', 'Tyrannosaurus Rex', 'Le Tyrannosaurus Rex, souvent abrégé en T-Rex, est l''un des plus grands carnivores terrestres de tous les temps. Ayant vécu à la fin du Crétacé, il y a environ 68 à 66 millions d''années, ce prédateur bipède se caractérisait par un crâne massif équilibré par une longue et lourde queue. Ses membres antérieurs étaient très courts et dotés de deux doigts griffus, contrastant avec ses membres postérieurs puissants. Ses dents, coniques et acérées, pouvaient mesurer jusqu''à 30 centimètres de long, racine comprise. Il était au sommet de la chaîne alimentaire de son époque, chassant probablement des hadrosaures, des cératopsiens et potentiellement des ankylosaures. Sa morsure est considérée comme l''une des plus puissantes de tout le règne animal.', 'Le tyran incontesté du Crétacé.', true),
(2, 'Béhémoth', 'Herbivore', 'Triceratops Horridus', 'Le Triceratops était un dinosaur herbivore quadrupède qui a vécu à la fin du Crétacé, aux côtés du T-Rex. Son nom signifie "tête à trois cornes". Il possédait une grande collerette osseuse et trois cornes faciales distinctives : une sur le museau et deux au-dessus des yeux. Cette collerette servait probablement de protection contre les prédateurs, mais aussi pour des rituels de parade nuptiale ou de domination. Mesurant jusqu''à 9 mètres de long et pesant jusqu''à 12 tonnes, ce dinosaur était un adversaire redoutable. Son bec puissant lui permettait de couper des végétaux coriaces, comme les cycas et les fougères, qu''il broyait ensuite avec ses batteries de dents.', 'La forteresse à trois cornes.', true),
(3, 'Abaddon', 'Carnivore', 'Spinosaurus Aegyptiacus', 'Le Spinosaurus est peut-être le plus grand de tous les dinosaurs carnivores, dépassant même le T-Rex en longueur. Il a vécu pendant le Crétacé, il y a environ 112 à 93 millions d''années. Sa caractéristique la plus frappante est la grande voile osseuse sur son dos, formée par de très longues épines vertébrales. La fonction de cette voile reste débattue : thermorégulation, parade ou intimidation. Des découvertes récentes suggèrent un mode de vie semi-aquatique. Son museau long et étroit, semblable à celui d''un crocodile, et ses dents coniques étaient parfaits pour attraper des poissons. Ses pattes arrière puissantes et ses pieds plats lui permettaient de se propulser dans l''eau.', 'Le prédateur des rivières du Crétacé.', false),
(4, 'Léviathan', 'Herbivore', 'Brachiosaurus Altithorax', 'Le Brachiosaurus était un immense dinosaur sauropode du Jurassique supérieur. Son nom signifie "lézard à bras", en référence à ses membres antérieurs qui étaient nettement plus longs que ses membres postérieurs. Cette particularité, combinée à un cou extrêmement long, lui donnait une posture inclinée, semblable à celle d''une girafe, lui permettant de brouter la cime des arbres. On estime qu''il pouvait atteindre une hauteur de 13 mètres et une longueur de 25 mètres. Malgré sa taille colossale, son crâne était relativement petit. Il se nourrissait de conifères, de ginkgos et de cycas, consommant plusieurs centaines de kilogrammes de matière végétale chaque jour pour subvenir à ses besoins énergétiques.', 'Le géant qui broutait les cimes.', true),
(5, 'Ziz', 'Carnivore', 'Velociraptor Mongolensis', 'Le Velociraptor, bien que popularisé comme un grand prédateur par le cinéma, était en réalité un dinosaur de la taille d''une dinde. Il a vécu au Crétacé supérieur. Ce carnivore bipède possédait une longue griffe en forme de faucille sur chaque pied, qu''il utilisait probablement pour maintenir ses proies. Des preuves fossiles solides, comme la présence de points d''ancrage pour les plumes sur ses os d''avant-bras, indiquent que le Velociraptor était couvert de plumes. Il chassait en meute de petits animaux, comme des reptiles et des mammifères primitifs. Son crâne était long et bas, et sa mâchoire était garnie d''environ 80 dents acérées.', 'Le chasseur à plumes agile et véloce.', true),
(6, 'Caïn', 'Carnivore', 'Allosaurus Fragilis', 'L''Allosaurus était un grand dinosaur théropode qui a vécu à la fin du Jurassique. C''était le prédateur dominant de son époque, avant l''avènement des tyrannosauridés. Il mesurait en moyenne 8,5 mètres de long, bien que certains spécimens suggèrent des tailles supérieures. Il possédait un grand crâne orné de petites cornes au-dessus des yeux. Ses mâchoires étaient remplies de dents acérées et recourbées. Ses bras à trois doigts, bien que plus grands que ceux du T-Rex, restaient relativement courts mais puissants, terminés par de grandes griffes. Il chassait probablement de grands herbivores comme le Stegosaurus et les sauropodes.', 'Le prédateur dominant du Jurassique.', false),
(7, 'Abel', 'Herbivore', 'Stegosaurus Stenops', 'Le Stegosaurus est l''un des dinosaurs les plus reconnaissables grâce à sa double rangée de plaques osseuses verticales le long de son dos et aux quatre pointes acérées au bout de sa queue (le "thagomizer"). Il a vécu à la fin du Jurassique. Les plaques servaient probablement à la thermorégulation ou à la parade, plutôt qu''à la défense. En revanche, sa queue était une arme défensive redoutable contre les prédateurs comme l''Allosaurus. Malgré sa grande taille, jusqu''à 9 mètres de long, son cerveau était remarquablement petit, de la taille d''une noix. C''était un herbivore qui se nourrissait de plantes basses.', 'La cuirasse ambulante du Jurassique.', true),
(8, 'Méthuselah', 'Herbivore', 'Ankylosaurus Magniventris', 'L''Ankylosaurus était un véritable char d''assaut blindé de la fin du Crétacé. Son corps était large, bas et couvert d''une armure de plaques osseuses épaisses, appelées ostéodermes, et de nodules. Même ses paupières étaient blindées. Sa caractéristique la plus distinctive était la grande masse osseuse au bout de sa queue, qu''il pouvait balancer avec une force immense pour briser les os de ses agresseurs. Cet herbivore se nourrissait de végétation basse, qu''il pouvait déchiqueter avec son bec édenté et ses petites dents en forme de feuille. Sa lenteur était compensée par une défense quasi impénétrable.', 'Le tank blindé du monde des dinosaurs.', true),
(9, 'Jonas', 'Piscivore', 'Pteranodon Longiceps', 'Bien que souvent associé aux dinosaurs, le Pteranodon était en réalité un ptérosaure, un reptile volant. Il a vécu au Crétacé supérieur. Il se distinguait par une grande crête osseuse à l''arrière de son crâne, dont la forme variait selon l''âge et le sexe, et qui servait peut-être de gouvernail ou de signe de reconnaissance. Son envergure pouvait atteindre plus de 7 mètres. Il était édenté et possédait un long bec pointu, idéal pour attraper des poissons en survolant les océans. Il passait probablement la plupart de son temps en vol plané au-dessus des mers, ne revenant à terre que pour se reproduire.', 'Le maître des cieux du Crétacé.', false),
(10, 'Salomon', 'Herbivore', 'Parasaurolophus Walkeri', 'Le Parasaurolophus était un hadrosaure (dinosaur à bec de canard) connu pour sa crête crânienne tubulaire et incurvée. Cette crête, qui pouvait atteindre 1,8 mètre de long, était creuse et reliée aux voies nasales. Les scientifiques pensent qu''elle était utilisée comme une chambre de résonance pour produire des sons graves et puissants, permettant la communication au sein du troupeau. Elle pouvait aussi servir de signal visuel pour la reconnaissance entre espèces ou individus. Ce dinosaur était un herbivore qui pouvait marcher sur deux ou quatre pattes, se nourrissant de plantes terrestres.', 'Le trombone du troupeau.', true),
(11, 'Samson', 'Herbivore', 'Diplodocus Carnegii', 'Le Diplodocus est l''un des plus longs dinosaurs connus, mesurant jusqu''à 27 mètres de long. Il a vécu à la fin du Jurassique. Sa morphologie était caractérisée par un cou et une queue extrêmement longs, avec un corps relativement court et des pattes robustes. Sa longue queue, composée de plus de 80 vertèbres, pouvait être utilisée comme un fouet pour se défendre contre les prédateurs. Contrairement au Brachiosaurus, son cou était probablement maintenu à l''horizontale. Il se nourrissait de fougères et d''autres végétations basses, utilisant ses dents en forme de crayon pour "peigner" les feuilles des branches.', 'Le géant à la queue de fouet.', true),
(12, 'Satan', 'Carnivore', 'Carnotaurus Sastrei', 'Le Carnotaurus, dont le nom signifie "taureau carnivore", était un théropode du Crétacé supérieur. Sa particularité la plus notable réside dans les deux cornes épaisses et pointues au-dessus de ses yeux, une caractéristique unique chez les grands carnivores. Son crâne était court et haut, et ses bras étaient ridiculement petits, encore plus réduits que ceux du T-Rex, et dépourvus de poignets fonctionnels. En revanche, ses pattes arrière étaient longues et puissantes, suggérant qu''il était un coureur très rapide. Il chassait probablement des proies de taille moyenne dans les plaines sud-américaines.', 'Le taureau carnivore aux bras minuscules.', false),
(13, 'Moïse', 'Herbivore', 'Iguanodon Bernissartensis', 'L''Iguanodon est l''un des premiers dinosaurs à avoir été découvert et nommé. Il a vécu au début du Crétacé. Cet herbivore pouvait alterner entre une posture bipède et quadrupède. Sa caractéristique la plus célèbre est le grand pouce en forme de pic sur chacune de ses mains. On a d''abord cru qu''il s''agissait d''une corne sur le nez, mais il s''agissait bien d''une arme défensive ou d''un outil pour casser des graines ou des fruits. Ses autres doigts étaient regroupés et formaient un "sabot" pour supporter son poids, tandis que son cinquième doigt, flexible, servait à saisir la nourriture.', 'Le dinosaur au pouce pointu.', true),
(14, 'Aaron', 'Omnivore', 'Oviraptor Philoceratops', 'L''Oviraptor, dont le nom signifie "voleur d''œufs", a été initialement mal nommé. Le premier fossile a été découvert sur un nid, et les paléontologues ont supposé qu''il volait les œufs. En réalité, il s''est avéré qu''il couvait ses propres œufs. Ce dinosaur du Crétacé supérieur, de la taille d''un homme, avait un bec édenté et puissant, peut-être utilisé pour écraser des coquilles d''œufs, des mollusques ou des fruits à coque. Il possédait une crête distinctive sur le crâne et était probablement couvert de plumes, avec de larges ailes qui l''aidaient à couver. Son régime alimentaire exact reste débattu, mais l''omnivorisme est l''hypothèse la plus probable.', 'Le parent dévoué au nom malheureux.', true),
(15, 'David', 'Herbivore', 'Pachycephalosaurus Wyomingensis', 'Le Pachycephalosaurus, ou "lézard à tête épaisse", est célèbre pour son crâne extrêmement épais et bombé, pouvant atteindre 25 cm d''épaisseur. Ce dôme osseux était entouré de petites bosses et de pointes osseuses. Il a vécu à la fin du Crétacé. La fonction de ce dôme est débattue : il servait peut-être à des combats intraspécifiques, où les individus se donnaient des coups de tête pour la domination ou les partenaires, un peu comme les mouflons modernes. C''était un bipède herbivore ou omnivore de taille moyenne, se nourrissant de feuilles, de graines et de fruits.', 'Le spécialiste du coup de tête.', false),
(16, 'Noé', 'Herbivore', 'Argentinosaurus Huinculensis', 'L''Argentinosaurus est un candidat au titre de plus grand animal terrestre de tous les temps. Ce titanosaure sauropode a vécu au milieu du Crétacé. Bien que les restes fossiles soient fragmentaires, les estimations basées sur les vertèbres massives (jusqu''à 1,6 mètre de haut) suggèrent une longueur de plus de 35 mètres et un poids approchant les 100 tonnes. Il se déplaçait lentement sur quatre pattes massives, en troupeaux, à travers les plaines d''Amérique du Sud, consommant d''énormes quantités de végétation pour maintenir sa masse corporelle. Sa taille seule était probablement sa principale défense contre les prédateurs géants comme le Giganotosaurus.', 'Le titan d''Argentine.', true),
(17, 'Nemrod', 'Carnivore', 'Giganotosaurus Carolinii', 'Le Giganotosaurus était un carcharodontosauridé qui rivalisait, voire dépassait, le T-Rex en taille. Vivant au milieu du Crétacé en Amérique du Sud, il était probablement le prédateur suprême de son écosystème, chassant d''immenses sauropodes comme l''Argentinosaurus. Son crâne était énorme, mais plus long et plus étroit que celui du T-Rex, et ses dents étaient plates et semblables à des lames, conçues pour trancher la chair plutôt que pour broyer les os. On pense qu''il chassait en groupe pour abattre des proies gigantesques, infligeant des blessures profondes et laissant la proie saigner jusqu''à la mort.', 'Le géant chasseur de titans.', true),
(18, 'Job', 'Omnivore', 'Therizinosaurus Cheloniformis', 'Le Therizinosaurus est l''un des dinosaurs les plus étranges jamais découverts. Ce théropode du Crétacé supérieur possédait des griffes démesurées sur ses membres antérieurs, pouvant atteindre un mètre de long. Malgré son appartenance au groupe des théropodes, majoritairement carnivores, son long cou, son petit crâne et ses dents en forme de feuille suggèrent un régime herbivore. Les griffes géantes n''étaient probablement pas utilisées pour la prédation, mais peut-être pour la défense ou pour ramener des branches à sa portée. Il avait un corps massif, des pattes robustes et était probablement couvert de plumes primitives.', 'L''énigme aux griffes démesurées.', false),
(19, 'Esther', 'Herbivore', 'Protoceratops Andrewsi', 'Le Protoceratops était un petit cératopsien du Crétacé supérieur, un parent du Triceratops. Il mesurait environ 1,8 mètre de long et possédait une grande collerette osseuse à l''arrière de son crâne, mais pas de véritables cornes sur le front, seulement une petite bosse sur le nez. La collerette variait en taille et en forme, servant probablement de signal visuel. Cet herbivore vivait en troupeaux dans des environnements désertiques. De nombreux nids fossilisés ont été découverts, indiquant qu''il prenait soin de ses petits. Il était une proie courante pour le Velociraptor, comme en témoigne le célèbre fossile des "dinosaurs combattants".', 'L''ancêtre à collerette du Triceratops.', true),
(20, 'Judas', 'Carnivore', 'Deinonychus Antirrhopus', 'Le Deinonychus est le dinosaur qui a inspiré les "Raptors" du film Jurassic Park. Vivant au début du Crétacé, il était bien plus grand que le Velociraptor, mesurant jusqu''à 3,4 mètres de long. Son nom, qui signifie "griffe terrible", fait référence à la grande griffe en forme de faucille de 12 centimètres qu''il portait sur le deuxième orteil de chaque pied. Cette griffe était une arme redoutable utilisée pour lacérer ses proies. Le Deinonychus était un prédateur intelligent et agile qui chassait probablement en meute pour s''attaquer à des proies plus grandes que lui, comme l''herbivore Tenontosaurus.', 'La "terrible griffe" qui chassait en meute.', true),
(21, 'Isaac', 'Herbivore', 'Corythosaurus Casuarius', 'Le Corythosaurus, dont le nom signifie "lézard au casque corinthien", était un hadrosaure doté d''une grande crête semi-circulaire sur le dessus de son crâne, ressemblant au casque des anciens soldats grecs. Tout comme celle du Parasaurolophus, cette crête était creuse et connectée au système respiratoire, servant à l''amplification sonore et à l''affichage visuel. Il a vécu à la fin du Crétacé en Amérique du Nord. C''était un herbivore qui se nourrissait de plantes coriaces comme les aiguilles de conifères, les graines et les brindilles, qu''il broyait avec ses centaines de petites dents.', 'Le dinosaur au casque de soldat grec.', false),
(22, 'Jacob', 'Carnivore', 'Ceratosaurus Nasicornis', 'Le Ceratosaurus était un théropode du Jurassique supérieur, reconnaissable à la corne distinctive sur son museau et aux deux petites crêtes au-dessus de ses yeux. Il mesurait environ 6 à 7 mètres de long. En plus de ses cornes crâniennes, il possédait une rangée de petites plaques osseuses (ostéodermes) le long de son dos. Ses dents étaient longues et en forme de lame. Il coexistait avec des prédateurs plus grands comme l''Allosaurus, ce qui suggère qu''il occupait une niche écologique différente, chassant peut-être des proies plus petites ou aquatiques près des cours d''eau.', 'Le carnivore à la corne nasale.', true),
(23, 'Ève', 'Herbivore', 'Maiasaura Peeblesorum', 'La Maiasaura, dont le nom signifie "bonne mère lézard", a fourni la première preuve de soins parentaux chez les dinosaurs. Cet hadrosaure du Crétacé supérieur vivait en grands troupeaux et construisait des nids en terre, où il pondait ses œufs en cercles. Les découvertes de squelettes de jeunes à l''intérieur et autour des nids suggèrent que les petits restaient au nid après l''éclosion et étaient nourris par les adultes jusqu''à ce qu''ils soient assez grands pour se débrouiller seuls. La Maiasaura était un grand herbivore, mesurant jusqu''à 9 mètres de long, avec un bec plat typique des hadrosaures et aucune crête crânienne élaborée.', 'La "bonne mère lézard" et ses nids.', true),
(24, 'Adam', 'Herbivore', 'Edmontosaurus Regalis', 'L''Edmontosaurus était l''un des plus grands hadrosaures, pouvant atteindre jusqu''à 13 mètres de long. Il a vécu à la toute fin du Crétacé et était contemporain du T-Rex, constituant l''une de ses principales proies. Il ne possédait pas de crête osseuse, mais des "momies" de dinosaurs exceptionnellement bien conservées montrent qu''il avait une crête charnue, semblable à celle d''un coq, sur sa tête. Il vivait en immenses troupeaux et migrait sur de longues distances. Ses mâchoires contenaient des milliers de dents organisées en batteries dentaires, parfaites pour broyer la végétation la plus résistante.', 'La proie favorite du T-Rex.', false),
(25, 'Gédéon', 'Carnivore', 'Utahraptor Ostrommaysi', 'L''Utahraptor est le plus grand membre connu de la famille des dromaeosauridés (les "raptors"). Découvert dans l''Utah, il a vécu au début du Crétacé. Il était bien plus grand et plus massif que le Deinonychus, pouvant atteindre 7 mètres de long et peser près de 500 kg. Sa griffe en faucille était proportionnellement énorme, mesurant plus de 22 centimètres de long. C''était un prédateur redoutable et puissant, capable de s''attaquer à de grands herbivores. Imaginez une version poids lourd du Velociraptor, et vous aurez une idée de la menace qu''il représentait.', 'Le plus grand et le plus redoutable des "raptors".', true),
(26, 'Rahab', 'Herbivore', 'Styracosaurus Albertensis', 'Le Styracosaurus était un cératopsien spectaculaire du Crétacé supérieur. Sa collerette osseuse était ornée de six longues cornes pointues, lui donnant une apparence de couronne d''épines. En plus de cela, il possédait une longue corne nasale, mais pas de cornes au-dessus des yeux comme le Triceratops. Cet arsenal servait à la fois à l''intimidation des rivaux et à la défense contre les prédateurs. Cet herbivore de taille moyenne (environ 5,5 mètres de long) vivait en troupeaux et se nourrissait de plantes basses.', 'Le dinosaur à la collerette épineuse.', true),
(27, 'Élie', 'Carnivore', 'Acrocanthosaurus Atokensis', 'L''Acrocanthosaurus était un grand théropode du début du Crétacé, antérieur au T-Rex. Son nom, qui signifie "lézard à hautes épines", vient des très longues épines neurales sur ses vertèbres, du cou à la queue, qui formaient une sorte de crête ou de voile basse sur son dos. C''était un prédateur de grande taille, atteignant 11,5 mètres de long. Des empreintes fossiles suggèrent qu''il chassait de grands sauropodes. Son crâne était long, bas et orné de crêtes rugueuses.', 'Le prédateur à la haute épine dorsale.', false),
(28, 'Lot', 'Herbivore', 'Euoplocephalus Tutus', 'L''Euoplocephalus était un ankylosauridé, un parent proche de l''Ankylosaurus. Son nom signifie "tête bien protégée". Tout comme son cousin plus célèbre, il était couvert d''une armure de plaques osseuses et de pointes, et possédait une massue caudale pour la défense. Il se distinguait par des bandes d''ostéodermes complexes et des cornes sur les coins arrière de sa tête. Il possédait également des plaques osseuses qui protégeaient ses paupières. C''était un herbivore lent qui vivait à la fin du Crétacé.', 'La tête bien protégée et blindée.', true),
(29, 'Sarah', 'Herbivore', 'Mamenchisaurus Sinocanadorum', 'Le Mamenchisaurus est célèbre pour avoir l''un des cous les plus longs de tous les animaux connus, pouvant atteindre jusqu''à 15 mètres de long, soit la moitié de sa longueur totale. Ce sauropode géant a vécu à la fin du Jurassique en Asie. Son cou était soutenu par des vertèbres cervicales extraordinairement longues et renforcé par des ligaments puissants. Cette adaptation lui permettait de balayer une vaste zone de végétation basse sans avoir à bouger son corps massif, économisant ainsi de l''énergie.', 'Le dinosaur au cou démesurément long.', true),
(30, 'Abraham', 'Omnivore', 'Gallimimus Bullatus', 'Le Gallimimus, dont le nom signifie "imitateur de poulet", était un ornithomimidé (dinosaur-autruche) du Crétacé supérieur. Il ressemblait effectivement à une autruche géante, avec un long cou, de longues pattes conçues pour la course rapide (il pouvait atteindre 60 km/h), et un bec édenté. Il mesurait jusqu''à 6 mètres de long. Son régime alimentaire était probablement omnivore, se nourrissant de plantes, d''insectes, de petits animaux et peut-être d''œufs. Il vivait en troupeaux dans des plaines ouvertes.', 'L''autruche géante du désert de Gobi.', false),
(31, 'Lazare', 'Carnivore', 'Tarbosaurus Baatar', 'Le Tarbosaurus est un grand tyrannosauridé d''Asie, très proche parent du T-Rex nord-américain. Certains scientifiques le considèrent même comme une espèce de Tyrannosaurus. Vivant à la fin du Crétacé, il était le prédateur suprême de son environnement. Ses caractéristiques sont très similaires à celles du T-Rex : une tête massive, de petites pattes avant à deux doigts et des pattes arrière puissantes. Il était légèrement plus petit et plus gracile que son cousin américain. Il chassait probablement des hadrosaures et des sauropodes.', 'Le T-Rex d''Asie.', true),
(32, 'Jézabel', 'Herbivore', 'Saltasaurus Loricatus', 'Le Saltasaurus était un titanosaure sauropode de la fin du Crétacé, mais il était relativement petit pour un sauropode, mesurant environ 12 mètres de long. Sa découverte a été révolutionnaire car elle a montré pour la première fois que certains sauropodes possédaient une armure. Son dos était couvert de milliers de petits nodules osseux (ostéodermes), avec quelques plaques plus grandes. Cette armure offrait une protection contre les prédateurs. Il vivait en troupeaux et pondait ses œufs dans de vastes aires de nidification communautaires.', 'Le petit sauropode qui portait une armure.', false),
(33, 'Josué', 'Carnivore', 'Albertosaurus Sarcophagus', 'L''Albertosaurus était un tyrannosauridé qui a vécu quelques millions d''années avant le T-Rex, au Crétacé supérieur. Il était plus petit et plus léger que son célèbre parent, avec une constitution plus gracile, ce qui suggère qu''il était un chasseur plus rapide et plus agile. Il mesurait environ 9 mètres de long. Des lits d''ossements contenant de multiples individus de différents âges ont été découverts, ce qui a conduit les scientifiques à émettre l''hypothèse qu''ils vivaient et chassaient en meutes, une stratégie complexe pour un grand prédateur.', 'Le cousin agile du T-Rex qui chassait en meute.', true),
(34, 'Ruth', 'Herbivore', 'Centrosaurus Apertus', 'Le Centrosaurus était un cératopsien qui vivait en immenses troupeaux à la fin du Crétacé. Il se caractérisait par une seule grande corne nasale, qui pouvait être courbée vers l''avant ou vers l''arrière, et une paire de petites cornes au-dessus des yeux. Sa collerette était ornée de petites cornes et de deux plus grandes cornes en forme de crochet qui pointaient vers l''avant. Des lits d''ossements massifs, contenant des milliers d''individus, suggèrent que des troupeaux entiers ont péri en tentant de traverser des rivières en crue.', 'Le cératopsien aux troupeaux immenses.', true),
(35, 'Emmanuel', 'Omnivore', 'Chirostenotes Pergracilis', 'Le Chirostenotes était un oviraptorosaure du Crétacé supérieur. Il était de taille moyenne, élancé, avec un long cou, de longues pattes et une crête sur la tête semblable à celle d''un casoar. Son nom signifie "mains étroites", en référence à ses longues mains à trois doigts. Son bec était édenté, et son régime alimentaire exact est incertain, mais probablement omnivore, incluant des plantes, des œufs et de petits animaux. C''était un dinosaur agile et rapide.', 'Le dinosaur agile aux mains étroites.', false),
(36, 'Siméon', 'Herbivore', 'Shunosaurus Lii', 'Le Shunosaurus était un sauropode de taille moyenne du Jurassique moyen, en Chine. Il mesurait environ 9,5 mètres de long. Sa caractéristique la plus intéressante est qu''il possédait une petite massue osseuse au bout de sa queue, munie de deux courtes pointes. C''est l''un des rares sauropodes connus à posséder une telle arme défensive. Son cou était relativement court pour un sauropode, et il se nourrissait probablement de végétation basse.', 'Le sauropode chinois à la queue massue.', true),
(37, 'Sodome', 'Carnivore', 'Majungasaurus Crenatissimus', 'Le Majungasaurus était le prédateur suprême de Madagascar à la fin du Crétacé. Ce théropode abélisauridé avait un crâne court et trapu, une seule corne arrondie sur le dessus de la tête, et des bras extrêmement courts. Des preuves fossiles solides, sous forme de marques de dents sur des os de Majungasaurus, indiquent qu''il était cannibale, se nourrissant de ses congénères, peut-être après des combats territoriaux ou en charognard.', 'Le prédateur cannibale de Madagascar.', true),
(38, 'Gomorrhe', 'Carnivore', 'Gorgosaurus Libratus', 'Le Gorgosaurus était un autre tyrannosauridé, très proche de l''Albertosaurus. Il a vécu au Crétacé supérieur en Amérique du Nord. Il était rapide et puissant, avec un sens de l''odorat très développé, comme les autres membres de sa famille. Plusieurs spécimens magnifiquement conservés, de jeunes à adultes, ont permis aux scientifiques d''étudier sa croissance et son développement. Il atteignait sa maturité rapidement, ce qui lui donnait un avantage de survie dans un environnement dangereux.', 'Le parent du T-Rex au cycle de vie rapide.', false),
(39, 'Hérode', 'Herbivore', 'Pachyrhinosaurus Canadensis', 'Le Pachyrhinosaurus était un cératopsien unique qui, au lieu de cornes, possédait une énorme et épaisse bosse osseuse sur son museau et au-dessus de ses yeux. Cette bosse servait probablement de base à une structure en kératine, et les mâles l''utilisaient pour des combats de poussée tête contre tête, similaires à ceux des bœufs musqués. Il vivait en troupeaux dans les régions arctiques de l''Amérique du Nord à la fin du Crétacé.', 'Le dinosaur à cornes sans cornes.', true),
(40, 'Salomé', 'Piscivore', 'Baryonyx Walkeri', 'Le Baryonyx était un spinosauridé du début du Crétacé. Son nom signifie "griffe lourde", en référence à une énorme griffe de 30 cm sur le pouce de chaque main. Il avait un long museau étroit rempli de dents coniques, très similaire à celui d''un crocodile. Des écailles de poisson ont été retrouvées dans son estomac fossilisé, confirmant son régime piscivore. Il utilisait probablement sa grande griffe comme un hameçon pour empaler les poissons hors de l''eau.', 'Le pêcheur à la griffe lourde.', true),
(41, 'Nazareth', 'Herbivore', 'Ouranosaurus Nigeriensis', 'L''Ouranosaurus était un iguanodontien d''Afrique du début du Crétacé. Tout comme le Spinosaurus, il possédait de très hautes épines vertébrales qui formaient une grande voile sur son dos. La fonction de cette voile est incertaine : thermorégulation, stockage de graisse (comme une bosse de chameau) ou affichage visuel. Il avait un large bec de canard et vivait probablement près des rivières et des deltas.', 'L''iguanodon à la grande voile dorsale.', false),
(42, 'Jéricho', 'Herbivore', 'Lambeosaurus Lambei', 'Le Lambeosaurus était un grand hadrosaure connu pour sa crête crânienne complexe. La crête avait la forme d''une hachette, avec une projection pointant vers l''avant et une autre, plus arrondie, vers l''arrière. Comme chez les autres hadrosaures à crête, elle était creuse et utilisée pour la vocalisation. La forme de la crête différait entre les espèces et probablement entre les sexes. Il vivait à la fin du Crétacé.', 'Le dinosaur à la crête en hachette.', true),
(43, 'Babel', 'Herbivore', 'Amargasaurus Cazaui', 'L''Amargasaurus était un sauropode relativement petit du début du Crétacé, mesurant environ 10 mètres de long. Sa caractéristique la plus frappante était une double rangée d''épines neurales extrêmement hautes et fines le long de son cou et de son dos. Ces épines ne formaient probablement pas une voile unique, mais plutôt une double rangée de pointes, peut-être recouvertes de peau. Elles servaient à la défense ou à l''affichage.', 'Le sauropode à la double crête d''épines.', true),
(44, 'Ézéchiel', 'Omnivore', 'Deinocheirus Mirificus', 'Le Deinocheirus, dont le nom signifie "main terrible", a longtemps été un mystère. Seuls ses bras gigantesques de 2,4 mètres de long, terminés par trois griffes impressionnantes, étaient connus pendant près de 50 ans. Des squelettes plus complets ont récemment révélé un animal étrange : un ornithomimosaure géant avec une bosse sur le dos, un bec de canard et un régime omnivore. Les griffes servaient probablement à creuser ou à rassembler des plantes.', 'Le mystère résolu de la "main terrible".', false),
(45, 'Ismaël', 'Herbivore', 'Therizinosaurus Cheloniformis', 'Le Therizinosaurus est un des dinosaurs les plus étranges. Appartenant au groupe des théropodes (majoritairement carnivores), il était pourtant herbivore. Ses caractéristiques les plus notables sont ses griffes démesurées, les plus longues connues de tout le règne animal, pouvant atteindre près d''un mètre. Il avait un long cou, un petit crâne et un corps volumineux. Ces griffes n''étaient pas pour la chasse, mais probablement pour la défense ou pour ramener des branches à portée de bouche.', 'Le faucheur herbivore aux griffes géantes.', true),
(46, 'Ésaü', 'Herbivore', 'Miragaia Longicollum', 'La Miragaia était un stégosauridé du Jurassique supérieur. Sa particularité était son cou exceptionnellement long, composé d''au moins 17 vertèbres, ce qui est plus que la plupart des sauropodes. Cette adaptation lui permettait de brouter une plus grande variété de végétation. Il possédait également les plaques et les pointes caudales typiques des stégosaures.', 'Le stégosaure au cou de girafe.', false),
(47, 'Mammon', 'Carnivore', 'Rugops Primus', 'Le Rugops était un abélisauridé du milieu du Crétacé en Afrique. Son nom signifie "face ridée", en référence à son crâne qui était parcouru de rainures pour des vaisseaux sanguins, suggérant la présence d''une sorte de revêtement sensoriel ou d''affichage en kératine. Son crâne était fragile, et ses dents petites, ce qui indique qu''il était probablement plus un charognard qu''un chasseur actif.', 'Le charognard à la face ridée.', true),
(48, 'Siloé', 'Herbivore', 'Nigersaurus Taqueti', 'Le Nigersaurus était un sauropode du Crétacé qui se distingue par son crâne extraordinairement adapté. Il avait une bouche très large et plate, semblable à un aspirateur, et plus de 500 dents fines et remplaçables, organisées en batteries. Il se nourrissait en broutant la végétation basse, comme de l''herbe ou des fougères, un peu comme une tondeuse à gazon préhistorique. Son cou était généralement orienté vers le bas.', 'L''aspirateur à fougères du Crétacé.', true),
(49, 'Magog', 'Carnivore', 'Mapusaurus Roseae', 'Le Mapusaurus était un carcharodontosauridé géant, parent du Giganotosaurus. Il a vécu au Crétacé supérieur. Des fossiles de plusieurs individus ont été trouvés ensemble, ce qui suggère fortement un comportement de chasse en meute. Cette stratégie leur aurait permis de s''attaquer aux plus grands animaux de tous les temps, les sauropodes titanosaures avec lesquels ils partageaient leur environnement.', 'Le chasseur en meute de titans.', true),
(50, 'Selah', 'Herbivore', 'Psittacosaurus Mongoliensis', 'Le Psittacosaurus, ou "lézard-perroquet", était un petit cératopsien primitif du début du Crétacé. Son nom vient de son bec haut et court, semblable à celui d''un perroquet. C''était un bipède agile qui possédait des structures uniques ressemblant à des piquants ou des soies le long de sa queue. Des fossiles exceptionnels ont permis de connaître la couleur et les motifs de sa peau, révélant un contre-ombrage (dos sombre, ventre clair) pour le camouflage.', 'Le petit lézard-perroquet à piquants.', false);

INSERT INTO TICKET (ticket_id, ticket_price, ticket_name, ticket_value) VALUES
(1, 50, 'Aventurier', 'aventurier'),
(2, 80, 'Explorateur', 'explorateur'),
(3, 115, 'Archéologue', 'archeologue'),
(4, 150, 'Paléontologue', 'paleontologue'),
(5, 250, 'Collectionneur chevronné', 'collectionneur');